# Generated by Django 4.2.5 on 2023-11-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_storagebox_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebox',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('GARAGE_BOX', 'Garage'), ('CELLAR', 'Cellar'), ('ATTIC', 'Attic'), ('ROOM', 'Room'), ('HANGAR_WAREHOUSE', 'Hangar / Warehouse'), ('PARKING', 'parking spot')], max_length=32, verbose_name="Type d'espace"),
        ),
    ]
