# Generated by Django 4.2.5 on 2023-11-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0003_alter_storagebox_image_1_alter_storagebox_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='storagebox',
            name='surface_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_place.surfacerange'),
        ),
    ]
