# Generated by Django 4.2.5 on 2023-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0005_remove_storagebox_surface_range_delete_surfacerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebox',
            name='image_1',
            field=models.ImageField(upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_2',
            field=models.ImageField(upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_3',
            field=models.ImageField(upload_to='box_picture'),
        ),
    ]
